2018-07-20 14:24:57,496 [Thread-2:140702032905984] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/project/blog_p/blog_app/views.py", line 18, in index
    return render(request, 'index.html', locals())
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    with context.bind_template(self):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_person_blog/blog/blog/lib/python3.5/site-packages/django/template/context.py", line 236, in bind_template
    updates.update(processor(self.request))
TypeError: global_setting() takes 0 positional arguments but 1 was given
2018-07-20 14:24:57,820 [Thread-3:140702024513280] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-07-20 14:40:43,772 [Thread-7:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:40:43,781 [Thread-8:140261791938304] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-20 14:40:43,791 [Thread-9:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-20 14:40:43,801 [Thread-10:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-20 14:40:43,816 [Thread-11:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-20 14:40:43,827 [Thread-12:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:40:44,076 [Thread-26:140261418071808] [django.request:152] [base:get_response] [WARNING]- Not Found: /favicon.ico
2018-07-20 14:40:49,276 [Thread-27:140261418071808] [django.request:152] [base:get_response] [WARNING]- Not Found: /news.html
2018-07-20 14:41:02,949 [Thread-28:140261418071808] [django.request:152] [base:get_response] [WARNING]- Not Found: /index.html
2018-07-20 14:41:07,959 [Thread-29:140261418071808] [django.request:152] [base:get_response] [WARNING]- Not Found: /news.html
2018-07-20 14:42:52,898 [Thread-31:140261791938304] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:42:52,905 [Thread-32:140261772441344] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-20 14:42:52,919 [Thread-33:140261783545600] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-20 14:42:52,934 [Thread-35:140261409679104] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-20 14:42:52,936 [Thread-34:140261764048640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-20 14:44:20,687 [Thread-3:140515678177024] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:44:20,691 [Thread-4:140515669784320] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-20 14:44:20,701 [Thread-5:140515661391616] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-20 14:44:20,715 [Thread-6:140515652736768] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-20 14:44:20,731 [Thread-7:140515644344064] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-20 14:47:37,595 [Thread-7:139661485553408] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:47:37,610 [Thread-8:139661521835776] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-20 14:47:37,619 [Thread-9:139661521835776] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-20 14:47:37,626 [Thread-10:139661521835776] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-20 14:47:37,635 [Thread-11:139661521835776] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-20 14:47:37,644 [Thread-12:139661485553408] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:48:36,607 [Thread-3:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-20 14:48:36,609 [Thread-4:139929936135936] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-20 14:48:36,625 [Thread-5:139929927743232] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-20 14:48:36,638 [Thread-6:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-20 14:48:36,654 [Thread-7:139929910695680] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-21 04:39:12,030 [Thread-12:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-21 04:39:12,041 [Thread-16:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-21 04:39:12,051 [Thread-17:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-21 04:39:12,061 [Thread-18:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-21 04:39:12,074 [Thread-19:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-21 04:39:12,091 [Thread-20:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-21 04:39:18,667 [Thread-35:139929936135936] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-21 04:39:18,679 [Thread-36:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-21 04:39:18,697 [Thread-37:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-21 04:39:18,710 [Thread-38:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-21 04:39:18,738 [Thread-39:139929936135936] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-21 04:39:20,805 [Thread-41:139929936135936] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-21 04:39:20,816 [Thread-42:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-21 04:39:20,833 [Thread-43:139929944528640] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-21 04:39:20,851 [Thread-44:139929936135936] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-21 04:39:20,858 [Thread-45:139929919350528] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 02:56:56,461 [Thread-12:139835912947456] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog_app/article/add/
Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 642, in get_form
    return modelform_factory(self.model, **defaults)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/forms/models.py", line 548, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/forms/models.py", line 257, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (template_name, registration_required, enable_comments) specified for Article

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1438, in changeform_view
    ModelForm = self.get_form(request, obj)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 646, in get_form
    % (e, self.__class__.__name__)
django.core.exceptions.FieldError: Unknown field(s) (template_name, registration_required, enable_comments) specified for Article. Check fields/fieldsets/exclude attributes of class ArticleAdmin.
2018-07-23 02:57:12,159 [Thread-13:139835912947456] [django.request:152] [base:get_response] [WARNING]- Not Found: /admim
2018-07-23 02:57:16,997 [Thread-14:139835912947456] [django.request:152] [base:get_response] [WARNING]- Not Found: /admim
2018-07-23 02:58:58,985 [Thread-2:140278863542016] [django.request:152] [base:get_response] [WARNING]- Not Found: /admim
2018-07-23 03:05:47,136 [Thread-20:140339490825984] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog_app/article/add/
Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2018-07-23 03:53:09,557 [Thread-35:140339516004096] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog_app/article/add/
Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2018-07-23 04:09:11,974 [Thread-53:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 04:09:12,011 [Thread-57:140547075327744] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:12,014 [Thread-52:140547092113152] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:12,017 [Thread-59:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:12,018 [Thread-58:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:12,055 [Thread-60:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 04:09:12,108 [Thread-62:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:12,111 [Thread-61:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:12,113 [Thread-63:140547092113152] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:12,128 [Thread-64:140547075327744] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:31,630 [Thread-84:140547075327744] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 04:09:31,637 [Thread-85:140547058542336] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:31,643 [Thread-87:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:31,648 [Thread-86:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:31,658 [Thread-88:140547184432896] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:31,711 [Thread-89:140547184432896] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:31,716 [Thread-90:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:31,718 [Thread-91:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:36,129 [Thread-93:140547184432896] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 04:09:36,138 [Thread-94:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:36,140 [Thread-95:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:36,142 [Thread-97:140547100505856] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:36,152 [Thread-96:140547058542336] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:36,219 [Thread-98:140547092113152] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:36,230 [Thread-99:140547058542336] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:36,240 [Thread-100:140547100505856] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:36,245 [Thread-101:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:40,806 [Thread-103:140547066935040] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 04:09:40,816 [Thread-104:140547100505856] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 04:09:40,836 [Thread-105:140547058542336] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:40,847 [Thread-106:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 04:09:40,849 [Thread-107:140547184432896] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 04:09:40,883 [Thread-108:140547184432896] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 04:09:40,895 [Thread-109:140547083720448] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 05:32:52,438 [Thread-29:140574469818112] [django.request:124] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog_app/article/add/
Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
pymysql.err.IntegrityError: (1048, "Column 'user_id' cannot be null")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1449, in changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1007, in save_model
    obj.save()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/cursors.py", line 308, in _query
    conn.query(q)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 820, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1002, in _read_query_result
    result.read()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 1285, in read
    first_packet = self.connection._read_packet()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 966, in _read_packet
    packet.check_error()
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/connections.py", line 394, in check_error
    err.raise_mysql_exception(self._data)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/opt/home_ext/maizi_python/Python_full_stack/django/django_demo/django_test/lib/python3.5/site-packages/pymysql/err.py", line 112, in _check_mysql_exception
    raise errorclass(errno, errorvalue)
django.db.utils.IntegrityError: (1048, "Column 'user_id' cannot be null")
2018-07-23 05:35:00,724 [Thread-39:140388513867520] [django.request:152] [base:get_response] [WARNING]- Not Found: /js/nav.js
2018-07-23 05:35:00,726 [Thread-38:140388601607936] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 05:35:00,729 [Thread-37:140388471904000] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 05:35:00,732 [Thread-40:140388480296704] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 05:35:00,734 [Thread-41:140388522260224] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
2018-07-23 05:35:00,811 [Thread-42:140388480296704] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a1.jpg
2018-07-23 05:35:00,817 [Thread-45:140388471904000] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a2.jpg
2018-07-23 05:35:00,821 [Thread-44:140388513867520] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a3.jpg
2018-07-23 05:35:00,827 [Thread-43:140388522260224] [django.request:152] [base:get_response] [WARNING]- Not Found: /images/a4.jpg
